language: php

matrix:
  include:
    - php: hhvm
      env: DB=mysqli FUNCTIONAL_TESTS=1
  allow_failures:
    - php: hhvm
  fast_finish: true

services:
  - redis-server

install:
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION $FUNCTIONAL_TESTS

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - travis/phing-sniff.sh $DB $TRAVIS_PHP_VERSION $FUNCTIONAL_TESTS
  - travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION $FUNCTIONAL_TESTS
  - sh -c "if [ '$FUNCTIONAL_TESTS' != '1' ]; then phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml --exclude-group functional,slow; fi"
  - sh -c "if [ '$FUNCTIONAL_TESTS' = '1' ]; then phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml --group functional; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$FUNCTIONAL_TESTS' != '1' -a '$DB' = 'mysqli' -a '$TRAVIS_PULL_REQUEST' != 'false' ]; then git-tools/commit-msg-hook-range.sh origin/$TRAVIS_BRANCH..FETCH_HEAD; fi"
  - ls -la travis/
  - cat travis/hhvm.log
  - cat travis/hhvm.log.log
  - cat travis/nginx.log
