parameters:
    core.template.cache_path: %core.root_path%cache/twig/

services:
    template.twig.environment:
        class: phpbb\template\twig\environment
        arguments:
            - @config
            - @path_helper
            - @service_container
            - @template.twig.phpbb_loader
            - %core.template.cache_path%
            - @ext.manager
            - @template.twig.loaders.collection
            - @template.twig.extensions.collection

    template.twig.lexer:
        class: phpbb\template\twig\lexer
        arguments:
            - @template.twig.environment

    template.twig.phpbb_loader:
        class: phpbb\template\twig\loader

    template.twig.loaders.collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: twig.loader }

    template.twig.extensions.collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: twig.extension }

    template.twig.extensions.phpbb:
        class: phpbb\template\twig\extension
        arguments:
            - @template_context
            - @user
        tags:
            - { name: twig.extension }
